name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable   # installs stable toolchain
      - name: Run tests
        run: cargo test --workspace --all-features --all-targets